[phases.setup]
cmd = "apt-get update && apt-get install -y python3 python3-pip"

[phases.install]
cmd = "pip3 install -r requirements.txt"

[phases.build]
cmd = ""

[phases.start]
cmd = "python3 bot.py"
